### PR TITLE
feat(es_extended/config.weapons.lua): Added new weapon weapon_heavyrifle

### PR DESCRIPTION
**Pull request by Cookiieezz**
Effected lines: 974-982 (weapon_heavyrifle)
location: es_extended/config.weapons.lua

### CODE REVIEW

**Comment by Cyzxin** [comment]
Can you format line 974 and add the correct spacing between variables? Just to look better and easier to read, look at the weapons below and above for examples

**Comment by Cookiieezz** [comment]
I actually dont know how to show the part which has been edited, I am not used with github :o

**Comment by mcNuggets1** [comment]
you didnt need to molest the whole file

**Comment by Cookiieezz** [comment]
"[...] molest [...]", damn, watch your mouth, hobby dev. It's a really offensive term that is used to assault sexually, so just don't use it, thanks!

**Comment by TheFantomas** [comment]
Formatted by me. Waiting for review by PR Manager @Gellipapa.

**Pull request merged**
