### PR TITLE
Update hu.lua

### PR DESCRIPTION
**Pull request by pecedevelopment**
corrected some spelling mistakes

### CODE REVIEW

**Comment by Gellipapa** [comment]
What is this "orrcsont csavar"?

**Comment by CsokiHUN** [comment]
> What is this "orrcsont csavar"?

i wait better translation solutions @Gellipapa

**Comment by Gellipapa** [comment]
> > What is this "orrcsont csavar"?
> 
> i wait better translation solutions @Gellipapa

Something like this "orrcsont hajlítás" or "orrcsont görbítés" or "orrcsont ferdítés"  choose one.

**Comment by pecedevelopment** [comment]
i don't know i just found a misspelling, but i will find a real translation

**Pull request closed without merging**
