### PR TITLE
feat(es_extended/server/main.lua): Player Connect Logging

### PR DESCRIPTION
**Pull request by thesysadmindev**
A new feature has been added, which allows for player identifiers to be captured and logged to a table (along with their last connect time), as well as the ability to send an embed to a Discord guild channel via ESX.DiscordLogFields. This can be disabled via a config option in config.lua with the webhook added into config.logs.lua which is mandatory if webhook logging is enabled.

### CODE REVIEW

**Comment by thesysadmindev** [comment]
@Gellipapa hey, it's ready to pull. All works are done.

**Review by Rav3n95 — CHANGES_REQUESTED** [review]
```lua
if not identifiers and not next(identifiers) then
  DropPlayer(source, "[ESX Blackbook] No identifiers were found when connecting, please reconnect.")
  return
end
```

**Review by thesysadmindev — COMMENTED** [review]
Change recommendation from @Rav3n95 has been implemented as requested.

**Comment by Rav3n95** [comment]
```lua
if Config.EnableConnectWebhook or Config.EnableConnectSQL then
    AddEventHandler('playerConnecting', function(name, setKick, def)
        local identifiers = GetPlayerIdentifiers(source)

        if not identifiers and not next(identifiers) then
            DropPlayer(source, "[ESX Blackbook] No identifiers were found when connecting, please reconnect.")
            return
        end

        local token = GetPlayerToken(source)
        local playerName = GetPlayerName(source)
        local temp = string.gsub(playerName, "[^a-zA-Z0-9]", "")
        local timestamp = os.date("%d/%m/%Y at %X")

        playerName = temp ~= "" and temp or playerName

        local data = {
            ['@name'] = playerName,
            ['@token'] = token,
            ["@timestamp"] = os.date("%Y-%m-%d %X")
        }

        for i = 1, #identifiers do
            data["@" .. ESX.Split(identifiers[i], ":")[1]] = identifiers[i]
        end

        if not Config.EnableConnectWebhook then
            ESX.DiscordLogFields("Connect", "Player Connection", "green", {
                { name = "Username",            value = playerName,       inline = false },
                { name = "Rockstar Identifier", value = data['@license'], inline = false },
                { name = "FiveM Token",         value = token,            inline = false },
                { name = "Connect Time",        value = timestamp,        inline = false }
            })
            return
        end

        if Config.EnableConnectSQL then
            MySQL.update(
            "INSERT INTO `blackbook` (`license`, `ip`, `name`, `xbl`, `live`, `discord`, `fivem`, `token`, `lastconnect`) VALUES (@license, @ip, @name, @xbl, @live, @discord, @fivem, @token, @timestamp) ON DUPLICATE KEY UPDATE `license`=@license, `ip`=@ip, `name`=@name, `xbl`=@xbl, `live`=@live, `discord`=@discord, `fivem`=@fivem, `token`=@token, `lastconnect`=@timestamp",
                data)
        end
    end)
end
```

**Pull request closed without merging**
