### PR TITLE
refactor(Player Class): Typing Code & Perf

### PR DESCRIPTION
**Pull request by Walker974**
268528063-d3191c7e-b258-4423-b73b-1204f47c2d1c

### CODE REVIEW

**Review by Thekuca — COMMENTED** [review]
I don't see the reason for parentheses IMO the code is cleaner without them. Other then that it's all good.

**Comment by Walker974** [comment]
Hey, yeah i agree with you.
Thank you
Have a good day

**Comment by benzon** [comment]
Wondering why you are using
local _GetPlayerPed = GetPlayerPed;
Instead of just local GetPlayerPed = GetPlayerPed

And why ; is added in the end, looks messy.

**Comment by Walker974** [comment]
Yes you can just use  local GetPlayerPed = GetPlayerPed
For ; in the end, it is just because I am familiar with C

**Comment by Walker974** [comment]
Hello @Gellipapa ! 
Good !

**Comment by Kenshiin13** [comment]
> Hi! @Walker974 Please remove ; and () in code. Keep the lua simple.

I can get behind not using semicolons, but I must say I find code less readable without '()'. Obviously, that is subjective.

**Comment by benzon** [comment]
> > Hi! @Walker974 Please remove ; and () in code. Keep the lua simple.
> 
> I can get behind not using semicolons, but I must say I find code less readable without '()'. Obviously, that is subjective.

Think it comes down to coding preferences and styles in the end, but it needs to be consistent throughout a project, and not end up having different coding styles, and formatting.

**Comment by benzon** [comment]
> Yes you can just use local GetPlayerPed = GetPlayerPed For ; in the end, it is just because I am familiar with C

Personally, I would prefer that natives are not redeclared (loaded) and then set to a new variable.

local GetPlayerPed = GetPlayerPed over local _GetPlayerPed = GetPlayerPed

**Comment by Kenshiin13** [comment]
>> 
> Think it comes down to coding preferences and styles in the end, but it needs to be consistent throughout a project, and not end up having different coding styles, and formatting.

Of course, I am not suggesting a change, everyone should stick to the style guidelines of the project.

**Review by Thekuca — APPROVED** [review]
Looks good

**Pull request merged**
