### PR TITLE
feat(server/functions): modify ESX.Jobs table and its related database tables on runtime

### PR DESCRIPTION
**Pull request by mahanmoulaei**
#### Add server-side functions to modify the core jobs table and database without the need to restart the server
Example Usage:

**ESX.AddJob**
```lua
-- adding single job
local job = {
    name = "JOB_NAME",
    label = "JOB_LABEL",
    whitelisted = true or false,
    grades = {
        ["0"] = {name = "trainee", label = "Trainee", salary = 100, skin_male = {}, skin_female = {}},
        ["1"] = {name = "experienced", label = "Experienced", salary = 150, skin_male = {}, skin_female = {}},
        ["2"] = {name = "boss", label = "Manager", salary = 200, skin_male = {}, skin_female = {}},
    }
}
ESX.AddJob(job)

-- adding multiple jobs
local jobs = {
    {
        name = "JOB_1_NAME",
        label = "JOB_1_LABEL",
        whitelisted = true or false,
        grades = {
            ["0"] = {name = "trainee", label = "Trainee", salary = 100, skin_male = {}, skin_female = {}},
            ["1"] = {name = "experienced", label = "Experienced", salary = 150, skin_male = {}, skin_female = {}},
            ["2"] = {name = "boss", label = "Manager", salary = 200, skin_male = {}, skin_female = {}},
        }
    },
    {
        name = "JOB_2_NAME",
        label = "JOB_2_LABEL",
        whitelisted = true or false,
        grades = {
            ["0"] = {name = "trainee", label = "Trainee", salary = 100, skin_male = {}, skin_female = {}},
            ["1"] = {name = "experienced", label = "Experienced", salary = 150, skin_male = {}, skin_female = {}},
            ["2"] = {name = "boss", label = "Manager", salary = 200, skin_male = {}, skin_female = {}},
        }
    }
}
ESX.AddJob(jobs)
```
<hr>

**ESX.UpdateJob**
```lua
-- updating single job
-- *for optional attributes => if provided it will update it, and if not provided it will use the previously saved values*
local job = {
    name = "JOB_NAME", -- mandatory
    label = "JOB_LABEL", -- optional
    whitelisted = true or false, -- optional
    grades = { -- optional
        ["0"] = {name? = "trainee", label? = "Trainee", salary? = 100, skin_male? = {}, skin_female? = {}}, -- all of the attributes are optional
        ["1"] = {name? = "experienced", label? = "Experienced", salary? = 150, skin_male? = {}, skin_female? = {}}, -- all of the attributes are optional
        ["2"] = {name? = "boss", label? = "Manager", salary? = 200, skin_male? = {}, skin_female? = {}}, -- all of the attributes are optional
    }
}
ESX.UpdateJob(job)

-- updating multiple jobs
-- *for optional attributes => if provided it will update it, and if not provided it will use the previously saved values*
local jobs = {
    {
        name = "JOB_1_NAME", -- mandatory
        label = "JOB_1_LABEL", -- optional
        whitelisted = true or false, -- optional
        grades = { -- optional
            ["0"] = {name? = "trainee", label? = "Trainee", salary? = 100, skin_male? = {}, skin_female? = {}}, -- all of the attributes are optional
            ["1"] = {name? = "experienced", label? = "Experienced", salary? = 150, skin_male? = {}, skin_female? = {}}, -- all of the attributes are optional
            ["2"] = {name? = "boss", label? = "Manager", salary? = 200, skin_male? = {}, skin_female? = {}}, -- all of the attributes are optional
        }
    },
    {
        name = "JOB_2_NAME", -- mandatory
        label = "JOB_2_LABEL", -- optional
        whitelisted = true or false, -- optional
        grades = { -- optional
            ["0"] = {name? = "trainee", label? = "Trainee", salary? = 100, skin_male? = {}, skin_female? = {}}, -- all of the attributes are optional
            ["1"] = {name? = "experienced", label? = "Experienced", salary? = 150, skin_male? = {}, skin_female? = {}}, -- all of the attributes are optional
            ["2"] = {name? = "boss", label? = "Manager", salary? = 200, skin_male? = {}, skin_female? = {}}, -- all of the attributes are optional
        }
    }
}
ESX.UpdateJob(jobs)
```
<hr>

**ESX.RemoveJob**
```lua
-- removing single job
local job = {
    name = "JOB_NAME"
}
ESX.RemoveJob(job)

-- removing multiple jobs
local jobs = {
    {
        name = "JOB_1_NAME"
    },
    {
        name = "JOB_2_NAME"
    }
}
ESX.RemoveJob(jobs)
```
<hr>

I will add two more functions in the near future if no one else does it:
~~ESX.UpdateJob~~(_**done**_) & ~~ESX.RemoveJob~~(_**done**_)

### CODE REVIEW

**Comment by mahanmoulaei** [comment]
From my side, this PR is complete now(I believe). Let me know if you encounter any issues with it.

**Comment by Gellipapa** [comment]
@mahanmoulaei Hi! Can you tell me a use case where this feature is used? When you thought about it, what was your idea of how to use it?

**Comment by mahanmoulaei** [comment]
> @mahanmoulaei Hi! Can you tell me a use case where this feature is used? When you thought about it, what was your idea of how to use it?

Hello,
Honestly, the explanation is straightforward, and there are a lot of use cases I can think of.

1-
Adding a job to the core directly within external and third-party resources without the need to provide a SQL for it.

2-
Modifying all attributes of a job like changing its label, whitelisted, grade label, grade name, grade salary, grade skins for employee, adding more grades & etc on runtime without the need to go to the database and change the desired data and have a permitted player to execute /refreshjobs command or do a server restart.

3-
Update players' jobs on any change applied to ESX.Jobs table without the need to re-assign them the job or have them to leave the server and join back again.

_etc and a lot more that I cannot think of(you tell me)...._

**Comment by TheFantomas** [comment]
Hello, after a professional consultation, we agreed that this pull request will not be accepted.

Why? In my opinion, it will not be used enough and we would rather rewrite the entire job system so that it is in the config and is completely removed from the database.

Thanks for the effort, regards
ESX Developer Team

**Comment by mahanmoulaei** [comment]
> it will not be used enough

What? Did you even read the use cases?

> we would rather rewrite the entire job system

I hope we see that soon, not like the on-duty system that was promised around a year ago...

> completely removed from the database

So you're going to close your eyes on the advantages of a database? Alright
However, if you rewrite the job system to be in a config, don't you think other resources still need to modify job attributes on runtime instead of restarting the core/server?

**Pull request closed without merging**
