### PR TITLE
refactor(es_extended/server/commands.lua): Fixed spawning vehicles in the air

### PR DESCRIPTION
**Pull request by WirzRexTon**
Avoid making the car spawn in the air, it is not visually beautiful.

### CODE REVIEW

**Comment by Mycroft-Studios** [comment]
This will cause Vehicles to have spasms and/or get stuck in the ground at times, doing Coords.z - 0.8 would be better 🙃

**Comment by TheFantomas** [comment]
Yep 1.0 is too much... I have tested on multiple vehicles and it is not good. You also have to test it on planes that jam the wheel in the road.

**Comment by CsokiHUN** [comment]
i think big vehicles stuck in ground

**Comment by Naifen-Phoxidas** [comment]
Use PlaceObjectOnGroundProperly(entity)

**Comment by Tinky124** [comment]
> Use PlaceObjectOnGroundProperly(entity)
SetVehicleOnGroundProperly(entity)

**Comment by TheFantomas** [comment]
Client side natives :( That would have to be done on the client side and that's "pointless"...

**Comment by CsokiHUN** [comment]
It might be better to do the grounding on the client side, but only for the admin command

**Comment by thelindat** [comment]
> Client side natives :( That would have to be done on the client side and that's "pointless"...

How is that "pointless"? The server has no concept of the ground, so if you want a vehicle to spawn on the ground then _only the client can do so_. It's not pointless for the same reason setting vehicle properties isn't useless.

Set state on the vehicle marking it as "just spawned", have the owner set it on the ground (and whatever else), then set the state to nil.

**Comment by TheFantomas** [comment]
This post will be closed due to inactivity - 20.2.2023

**Comment by TheFantomas** [comment]
Unfortunately closed due to inactivity - 3 Weeks without any response.

In this state, pr cannot be merged. It doesn't solve the problem, rather it breaks the matter even more.

Thanks to everyone who participated in the development of this pr. If someone wants to fix this, I'd be happy if you create a new pr where this will be fixed.

For the entire developer team
Fantík <3

**Pull request closed without merging**
