### PR TITLE
Callback await

### PR DESCRIPTION
**Pull request by CsokiHUN**
- [x] ESX.TriggerServerCallback.Await
- [ ] ESX.TriggerClientCallback.Await

### CODE REVIEW

**Comment by CsokiHUN** [comment]
> @CsokiHUN Hi! What is the status here? Need to test?

Please test, but only the server side callback is ready

**Comment by mahanmoulaei** [comment]
> I test this @CsokiHUN. Its working good. You can add ESX.TriggerClientCallback.Await.

I'm not really sure what did you test and how did you find out _it's woking good_, because Lua metamethods cannot be msgpacked in FiveM.

**Comment by Gellipapa** [comment]
@TheFantomas @CsokiHUN What a current status? Were you able to test it?

**Comment by CsokiHUN** [comment]
> I'm not really sure what did you test and how did you find out _it's woking good_, because Lua metamethods cannot be msgpacked in FiveM.

you are absolutely right, I close PR

**Pull request closed without merging**
