### PR TITLE
refactor(core): reformatting code with prettier

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by Rav3n95** [comment]
Thanks a lot, thing is im more then sure some of the code changed in the mean time.

**Comment by MoskalykA** [comment]
> Thanks a lot, thing is im more then sure some of the code changed in the mean time.

I've just looked, obviously nothing has changed.

**Comment by MoskalykA** [comment]
Hi, any news?

**Comment by TheFantomas** [comment]
> Hi, any news?

Requested review from prs manager.

**Review by CsokiHUN — APPROVED** [review]

**Pull request merged**
