### PR TITLE
refactor(client/functions): refactor getting burst tyres on vehicle

### PR DESCRIPTION
**Pull request by itsmaty**
i refactored the logic used to determine what tyres of an vehicles are burst

just get the wheel count and then iterate from 0 to the wheel count -1 and the current iteration is the tyre index

### CODE REVIEW

**Comment by Gellipapa** [comment]
Hi! @itsmaty  Thank you for your refactor. I'd like to ask you to open a new PR because 1.10.5 updates have just been added and they are no longer part of main since it was added.

**Comment by Gellipapa** [comment]
Update your branch and open new PR thank you. I fixed dev branch.

**Comment by itsmaty** [comment]
Hey @Gellipapa,
i will just create a new Fork and commit the chnages again.

So should i commit to the main or dev branch?

**Comment by Gellipapa** [comment]
> Hey @Gellipapa, i will just create a new Fork and commit the chnages again.
> 
> So should i commit to the main or dev branch?

@itsmaty Hi! All the time open pr in main branch. We change branch and merge develop after we release merge main this is workflow. Thanks. 

(My mistake i don't synch latest hotfix release to dev, sorry)

**Comment by itsmaty** [comment]
@Gellipapa 

Opend new PR in https://github.com/esx-framework/esx_core/pull/1333

**Pull request closed without merging**
