### PR TITLE
refactor: unused varargs

### PR DESCRIPTION
**Pull request by MoskalykA**
Hi, I suggest deleting this vararg which seems to be unused

### CODE REVIEW

**Comment by Gellipapa** [comment]
@MoskalykA Hi! What happens if somebody wants to pass some property of the item, or some extra variable that they want to get back in the callback?

```lua
function useHealthKit(source, item, healthRestoreAmount)
    print("Health kit used by player " .. source .. ". Restores " .. healthRestoreAmount .. " health.")
end

Core.UsableItemsCallbacks["healthkit"] = useHealthKit
```

```lua
ESX.UseItem(123, "healthkit", 50)
```

**Comment by Gellipapa** [comment]
So clearly we cannot accept it because we use it.

**Comment by MoskalykA** [comment]
I agree, although I haven't found any use for it ([search](https://github.com/search?q=fivem+ESX.UseItem&type=code)), otherwise you'd have to use a table rather than a vargarg, and there should be a distinct difference in performance.

**Comment by Gellipapa** [comment]
> I agree, although I haven't found any use for it ([search](https://github.com/search?q=fivem+ESX.UseItem&type=code)), otherwise you'd have to use a table rather than a vargarg, and there should be a distinct difference in performance.

Yes in the past a table might have been better but now you can still pass a table because of this operator, but if you don't add a table and overwrite or delete it you break the system.

**Pull request closed without merging**
