### PR TITLE
Update de.lua

### PR DESCRIPTION
**Pull request by TBosstradamus**
Grammar and spelling errors fixed

### CODE REVIEW

**Comment by Gellipapa** [comment]
@TBosstradamus  Hi! Thank you for update de.lua. Looks cool.

**Review by Gellipapa — APPROVED** [review]

**Comment by TheBlokker** [comment]
As German native speaker i can say that is correct

**Comment by Gellipapa** [comment]
Hi! @TBosstradamus please resolve merge conflict, and next time please use dev branch for pull request, we don't merge main branch instantly.

**Comment by TheFantomas** [comment]
Hello,

In dev brach it should already be fixed by our translator @Lenny822. Of course, I will be happy if you take another look at it, and if you have a different opinion, do not hesitate to correct this.

If this question stays here for more than a week without your answer, it will be automatically closed by our team.

With regards and respect
Management
@TheFantomas

**Comment by Lenny822** [comment]
> Hello,
> 
> In dev brach it should already be fixed by our translator @Lenny822. Of course, I will be happy if you take another look at it, and if you have a different opinion, do not hesitate to correct this.
> 
> If this pr stays here for more than a week without your answer, it will be automatically closed by our team.
> 
> With regards and respect Management @TheFantomas

To be honest, that isnt my translation, mine is idk where

**Pull request closed without merging**
