### PR TITLE
refactor: disable action events

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by Gellipapa** [comment]
Hi! @MoskalykA  Why would it make sense to turn off something that helps development and some scripts are based on it? like esx_hud, esx_cruisecontrol etc.

**Comment by MoskalykA** [comment]
> Hi! @MoskalykA Why would it make sense to turn off something that helps development and some scripts are based on it? like esx_hud, esx_cruisecontrol etc.

That's why it's possible to deactivate it. Personally, I don't use it and would like to have as few operations as possible.

**Comment by Gellipapa** [comment]
> > Hi! @MoskalykA Why would it make sense to turn off something that helps development and some scripts are based on it? like esx_hud, esx_cruisecontrol etc.
> 
> That's why it's possible to deactivate it. Personally, I don't use it and would like to have as few operations as possible.

What disadvantage do you have if you don't use it and it's not switched off? 

We have to think of the majority here, if there is no real world example that makes it useful we will not accept it, because it can generate an error if someone turns it off and later starts using, say, esx_hud.

**Comment by MoskalykA** [comment]
> What disadvantage do you have if you don't use it and it's not switched off?
> 
> We have to think of the majority here, if there is no real world example that makes it useful we will not accept it, because it can generate an error if someone turns it off and later starts using, say, esx_hud.

There's no disadvantage if you use this system, but if you don't then you might as well disable it.

"because it can generate an error if someone turns it off and later starts using"
This could be the same with any similar changes, why did you do it with `getSharedObject` then?

**Comment by Gellipapa** [comment]
> > What disadvantage do you have if you don't use it and it's not switched off?
> > We have to think of the majority here, if there is no real world example that makes it useful we will not accept it, because it can generate an error if someone turns it off and later starts using, say, esx_hud.
> 
> There's no disadvantage if you use this system, but if you don't then you might as well disable it.
> 
> "because it can generate an error if someone turns it off and later starts using" This could be the same with any similar changes, why did you do it with `getSharedObject` then?

I didn't do that, that was another development team, but now I'm not going to bullshit people into putting it back, I hope you understand thanks.

**Comment by Gellipapa** [comment]
Of course, there's only one level after which it's not worth configuring, because then everything that's not used by someone could be turned off. That's why the getSharedObject should not be enabled/disabled because everyone would set it to true and use the old method.

These addeventhandlers don't break performance, because they run when someone triggers them.

**Comment by MoskalykA** [comment]
How do we detect their triggers?

**Comment by Gellipapa** [comment]
> 

What do you mean? You can see example in esx_hud, or esx_cruisecontrol.

**Comment by MoskalykA** [comment]
> What do you mean? You can see example in esx_hud, or esx_cruisecontrol.

I wanted you to point out the triggering of these events but oh well. Personally, having an iteration every 200 milliseconds for a system I don't use bothers me.

**Comment by Kenshiin13** [comment]
> > What do you mean? You can see example in esx_hud, or esx_cruisecontrol.
> 
> I wanted you to point out the triggering of these events but oh well. Personally, having an iteration every 200 milliseconds for a system I don't use bothers me.

Script developers may rely on these events, could be kind of annoying if the user turns it off and wonders why his script does not work.

**Comment by MoskalykA** [comment]
> Script developers may rely on these events, could be kind of annoying if the user turns it off and wonders why his script does not work.

But why assume that a person would deactivate something he doesn't know the meaning of, and then even if he did, that person would be helped?

**Comment by Kenshiin13** [comment]
> But why assume that a person would deactivate something he doesn't know the meaning of, and then even if he did, that person would be helped?

People turn stuff off they don't know about all the time. 
I'm not necessarily against the changes, just making sure we consider all the outcomes.

**Comment by Gellipapa** [comment]
@MoskalykA 

We will not accept it because there is no use case where it would be useful to introduce it. 99% of people would leave it as it is because it would be the default.(true) If it bothers you then comment it out in your own system or implement it yourself. 

Thank you for your understanding.

**Pull request closed without merging**
