### PR TITLE
fix: fixed validation check in commands

### PR DESCRIPTION
**Pull request by tony-stark-17**

### CODE REVIEW

**Comment by Gellipapa** [comment]
@tony-stark-17 Hi! Can you send me any use case? Why needed "or" conditon?

**Comment by tony-stark-17** [comment]
> @tony-stark-17 Hi! Can you send me any use case? Why needed "or" conditon?

The /dv command usually doesn't require an argument but even though validate is false it asks for one.

**Comment by Gellipapa** [comment]
> > @tony-stark-17 Hi! Can you send me any use case? Why needed "or" conditon?
> 
> The /dv command usually doesn't require an argument but even though validate is false it asks for one.

Okey, can you test current dev branch and reply me?

**Comment by tony-stark-17** [comment]
> > > @tony-stark-17 Hi! Can you send me any use case? Why needed "or" conditon?
> > 
> > 
> > The /dv command usually doesn't require an argument but even though validate is false it asks for one.
> 
> Okey, can you test current dev branch and reply me?

The Dev branch works as expected!

**Comment by tony-stark-17** [comment]
Also updated the identifier fetch method

**Comment by Gellipapa** [comment]
@tony-stark-17  Hi! Thanks, but the changes are already included in the dev you posted. So I'm closing the issue. 

Note: We work only dev branch, if you want open pull request please checkout dev branch.

**Pull request closed without merging**
