### PR TITLE
feat(esx/server/classes/player): Add Job Duty

### PR DESCRIPTION
**Pull request by Thekuca**

### CODE REVIEW

**Review by CsokiHUN — APPROVED** [review]
Looks good but, do we add it to the database save?

**Comment by TheFantomas** [comment]
> Looks good but, do we add it to the database save?

Maybe we can add it to the database. Is good suggestion from you :D

**Comment by Mycroft-Studios** [comment]
this a bad idea, its basically the exact same system that was in before and benzo had to remove. for this to work it has to be added into all resources otherwise there is no point in it, just adding a variable in doesn't add the functionality, that part lies in the jobs themselves

**Comment by TheFantomas** [comment]
> this a bad idea, its basically the exact same system that was in before and benzo had to remove. for this to work it has to be added into all resources otherwise there is no point in it, just adding a variable in doesn't add the functionality, that part lies in the jobs themselves

This will be integrated in the next release so 1.9.5. It will be integrated into all jobs, don't worry :D

**Comment by Mycroft-Studios** [comment]
> > this a bad idea, its basically the exact same system that was in before and benzo had to remove. for this to work it has to be added into all resources otherwise there is no point in it, just adding a variable in doesn't add the functionality, that part lies in the jobs themselves
> 
> This will be integrated in the next release so 1.9.5. It will be integrated into all jobs, don't worry :D

if its integrated in thats fine, but the PR alone is a bad idea :)

**Pull request closed without merging**
