### PR TITLE
Feature Request 1143: Added 'coordinate' arg type for ESX.RegisterCommand()

### PR DESCRIPTION
**Pull request by Kenshiin13**
#### Description
This pull request introduces a new argument type, 'coordinate', to the existing `setcoords` command. The 'coordinate' argument type allows more flexible input formats for specifying coordinates, accommodating user feedback and enhancing usability. The changes are made in response to a feature request discussed in [GitHub Issue #1143](https://github.com/esx-framework/esx_core/issues/1143).

#### Changes Made
In this pull request, a new argument type 'coordinate' has been added to the `setcoords` command. The code snippet for handling this argument type has been enhanced as follows:

```lua
elseif v.type == 'coordinate' then
    local coord = tonumber(args[k]:match("(-?%d+%.?%d*)"))
    if not coord then
        error = TranslateCap('commanderror_argumentmismatch_number', k)
    else
        newArgs[v.name] = coord
    end
end
```
This allows users to provide coordinates in various formats such as:

- {x:-1, y:2, z:3}
- {x=-1.01, y=2.02, z=3.03}
- -1, 2, 3
- 474.08966064453, -1718.7073974609, 29.329517364502

#### Reasoning
The motivation behind this change is to enhance the user experience when utilizing the setcoords command. The feature request (#1143) highlighted the need for a more permissive coordinate input format to make the command more versatile and user-friendly. The new 'coordinate' argument type accommodates a wider range of coordinate representations, allowing users to input coordinates in a format that suits their preference. This change seeks to improve the overall usability and flexibility of the command, promoting a more intuitive interaction for users working with coordinates.

#### Inspiration

These improvements draw inspiration from the setCoords handler in [txAdmin](https://github.com/tabarra/txAdmin), which has demonstrated exceptional effectiveness in facilitating the use of multiple coordinate formats, greatly enhancing user convenience. The provided test cases are directly sourced from the txAdmin codebase, which serves as a reliable reference for the proposed enhancements.

Thank you for considering this enhancement to the setcoords command. Your feedback and suggestions are appreciated.

[Related GitHub Issue #1143](https://github.com/esx-framework/esx_core/issues/1143)

### CODE REVIEW

**Review by CsokiHUN — APPROVED** [review]

**Comment by Gellipapa** [comment]
Hi! @Kenshiin13 I like your suggestion, I'll test it tomorrow and if it works and handles everything I've done so far I'll shut up and marinate it. This is a better implementation. Thanks a lot.

**Comment by Kenshiin13** [comment]
> Hi! @Kenshiin13 I like your suggestion, I'll test it tomorrow and if it works and handles everything I've done so push and merge it. This is a better implementation. Thanks a lot.

Thank you, let me know if there are any unexpected issues!

**Comment by Gellipapa** [comment]
@Kenshiin13 Hi! Well done, I'll tested and merged.

**Comment by tekkenkkk** [comment]
@Kenshiin13 thank you 🙌

**Pull request merged**
