### PR TITLE
refactor(esx_core): spawning system, general code refactor

### PR DESCRIPTION
**Pull request by Thekuca**
Replace spawnmanager player spawning system with esx player spawning system

### CODE REVIEW

**Comment by Thekuca** [comment]
Everything works, tested by me.

**Review by Thekuca — COMMENTED** [review]
this is being tested currently

**Comment by Gellipapa** [comment]
@Thekuca Hi! Csoki callback is added in a separate PR because it's very risky that something will break and it's difficult to test. 

So always open a PR for a context. Callbacks are now a separate topic so you need a separate PR for it. Thanks.

**Comment by Thekuca** [comment]
@Gellipapa tested, works.

**Comment by Gellipapa** [comment]
> @Gellipapa tested, works.

Hi! Thanks i will test it soon.

**Pull request closed without merging**
