### PR TITLE
feat(es_extended): callback functions, vehicle type

### PR DESCRIPTION
**Pull request by CsokiHUN**
### New functions:
- ESX.RegisterClientCallback, ESX.TriggerClientCallback
- ESX.GetVehicleType *(client)*

### Old server callback refactored and moved to the modules folder
Server side ESX.GetVehicleType has been optimized

### CODE REVIEW

**Comment by Mycroft-Studios** [comment]
THIS IS NOT A GOOOD IDEA
client call-backs are vulnerable as shit, the Client should **never** have control over data. this will just lead to cheats being able to abuse resources even easier

**Comment by CsokiHUN** [comment]
> THIS IS NOT A GOOOD IDEA client call-backs are vulnerable as shit, the Client should **never** have control over data. this will just lead to cheats being able to abuse resources even easier

This is not for vital data, only for data such as the type of vehicle

**Comment by Mycroft-Studios** [comment]
> > THIS IS NOT A GOOOD IDEA client call-backs are vulnerable as shit, the Client should **never** have control over data. this will just lead to cheats being able to abuse resources even easier
> 
> This is not for vital data, only for data such as the type of vehicle

Users won't use it that way, that's why I locked it down to that one specific function, because the community won't realise how to use it and just use client data and then boom , suddenly all the work on extra security to esx is useless

**Comment by CsokiHUN** [comment]
Don't include a feature because you think people don't understand it. The basic thing for anyone who makes a script is 'never trust client'. 
Other FiveM frameworks have these features, why not create them?
But we'll wait and see what other people say

**Pull request merged**
