### PR TITLE
tweak: use txAdmin locale by default 

### PR DESCRIPTION
**Pull request by Mycroft-Studios**
by default, use the txAdmin locale, unless a `esx:locale` is specified.
This allows people to change languages easier, since everything will be in the same place, and if they want to specify a different language for ESX, then they can do.

This also wont break anything, since it wont affect existing users whom will aready have the `esx:locale` set

### CODE REVIEW

**Comment by Gellipapa** [comment]
@Mycroft-Studios Hi! 

Why not make it so that you include the get-er of txadmin in the esx locale, if it is given before then it will use it anyway if not given then txadmin will use it and if txadmin is not given then say a default en and then you don't need the extra variables and additional conditions.

**Comment by Mycroft-Studios** [comment]
wdym by that?

**Comment by Gellipapa** [comment]
Something like that.
If there is no esx:locale it will check if there is something in txadmin if there is it will set it if not it will use 'en'.

`Config.Locale = GetConvar("esx:locale", GetConvar("txAdmin-locale", "en"))`

**Comment by Mycroft-Studios** [comment]
> Something like that. If there is no esx:locale it will check if there is something in txadmin if there is it will set it if not it will use 'en'.
> 
> `Config.Locale = GetConvar("esx:locale", GetConvar("txAdmin-locale", "en"))`

there is a chance the txAdmin-locale = "custom", and therefore that needs to be taken into account

**Comment by Gellipapa** [comment]
> > Something like that. If there is no esx:locale it will check if there is something in txadmin if there is it will set it if not it will use 'en'.
> > `Config.Locale = GetConvar("esx:locale", GetConvar("txAdmin-locale", "en"))`
> 
> there is a chance the txAdmin-locale = "custom", and therefore that needs to be taken into account

Hm, and what language is custom? Could this be a design flaw? I think you should also specify "en" instead of custom in default, I don't understand what the custom value is in txadmin.

`Config.Locale = esxLocale ~= "none" and esxLocale or (txAdminLocale ~= "custom" and txAdminLocale or "en")`

**Comment by Mycroft-Studios** [comment]
People love todo things the wrong way, so custom is there for to stop people breaking stuff if they edit the tx translations in the wrong way.

And while the one liner would work, i feel like its.. less readable

**Comment by Gellipapa** [comment]
> People love todo things the wrong way, so custom is there for to stop people breaking stuff if they edit the tx translations in the wrong way.
> 
> And while the one liner would work, i feel like its.. less readable

I understand, but if something is not ready, why is it not easier to set the language to "en" as default, rather than adding a custom type which would result in "en" anyway. 

Yes there are cases where it's not readable if you shortcut, but personally this is an easy readable version and I find it unnecessary to make more conditonal.

**Review by Gellipapa — APPROVED** [review]

**Pull request merged**
