### PR TITLE
Update de.lua

### PR DESCRIPTION
**Pull request by Lenny822**
Because mine wasnt uploaded or something, this is the newer and updated one.

### CODE REVIEW

**Comment by Gellipapa** [comment]
@Lenny822 Hi! Please use dev branch and resolve merge conflict. We don't merge instanly to main.

**Comment by Lenny822** [comment]
Okay, i will do @Gellipapa

**Comment by Gellipapa** [comment]
@Lenny822 Thank you.

**Comment by Gellipapa** [comment]
@Lenny822 Open new pull request and fix translate. I revert your commit because your de locales 700 rows default EN 340 rows. I think you don't delete main branch locales. Open new pull request and use dev branch.

**Pull request merged**
